### ISSUE TITLE
[Feature] custom increment function

### ISSUE THREAD

**Issue by Pagwin2** [GalaxySH/cr-counting-bot#20]
I was thinking it'd be cool if admins on a server could set a custom increment function where you specify an equation that determines the next value that a user should send in the counting channel, for example `c?increment f(x)=(x^(1/2)+1)^2` would have it so the values the users have to put in are 1, 4, 9, 16, 25, 36, ect. where x is the previous value output from the equation and the first value put in as x(before the first user provides a number) is 0

**Comment by GalaxySH** [comment]
I am not sure how to proceed on this.

**Comment by mchrisgm-backup** [comment]
where would the function be displayed for the users to know which value comes next?

**Comment by Pagwin2** [comment]
> where would the function be displayed for the users to know which value comes next?

@MChrisGM  `c?next` would be used to find the next value and if a user wants to know the increment function you could probably output it if you do something like `c?increment` without any arguments or maybe use a different command to display the increment function like `c?displayinc`
