### ISSUE TITLE
[Feature request] personal saves reward

### ISSUE THREAD

**Issue by Vazyriqx** [GalaxySH/cr-counting-bot#53]
You should add an option to build up personal saves for sending correct numbers so if you have said 10 correct numbers got 1 personal save or something. could add a cap to stored saves aswell.

**Comment by GalaxySH** [comment]
Notes: As of this message, when someone starts counting, a counter begins in the bot. If 50 correct counts **in a row** are reached, a personal-save will be rewarded to the user. Messing up will restart the 0-50 counter.
